name: Python Application Workflow

on: [push]

jobs:
  build-and-test2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    # - name : Installer pandas et numpy
    - name : Installation propre
      run: pip install -r requirements.txt

    - name : executer un code python qui import pandas et print('pandas dispo')
      run: app2.py
    